def get_risk_color(urgency_level: str) -> str:
    """
    Returns the CSS class corresponding to the urgency level generated by the AI.
    """
    mapping = {
        "Normal": "risk-normal",
        "Needs Attention": "risk-attention",
        "Consult Doctor Soon": "risk-consult",
        "Emergency": "risk-emergency"
    }
    return mapping.get(urgency_level, "risk-normal")

def get_value_color(status: str) -> str:
    """
    Returns the CSS class for abnormal value high/low status.
    """
    mapping = {
        "High": "value-high",
        "Low": "value-low",
        "Normal": "value-normal"
    }
    return mapping.get(status, "value-normal")
